[package]
name = "rusty_brain"
version = "0.1.0"
authors = ["Farish Irfan <farish.irfan_0905@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
